"""Generate Claude discovery entrypoints from the shared agent skills."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


GENERATED = "<!-- Generated by python -m tools.agent_setup; edit the canonical source. -->"
REPO_ROOT = Path(__file__).resolve().parent.parent


def _wrapper(source: Path, root: Path) -> str:
    text = source.read_text(encoding="utf-8")
    metadata = ""
    if source.name == "SKILL.md":
        match = re.match(r"\A---\n(.*?)\n---(?:\n|$)", text, re.DOTALL)
        if not match or not all(
            re.search(rf"^{field}:\s*\S", match[1], re.MULTILINE)
            for field in ("name", "description")
        ):
            raise ValueError(f"{source}: skill frontmatter needs name and description")
        metadata = match[0].rstrip() + "\n"
    path = source.relative_to(root).as_posix()
    return (
        metadata + "\n" + GENERATED + "\n\n"
        f"Read `{path}` in full and follow its instructions.\n"
        "This file is a discovery entrypoint; the linked file is the complete\n"
        "shared procedure. Resolve its supporting resources from the canonical\n"
        "file's directory. Read `AGENTS.md` for the shared rules and runtime adapter.\n"
    ).lstrip("\n")


def sync(root: Path, *, check: bool = False) -> list[str]:
    """Return changed root-relative paths, optionally without writing.

    Only canonical Markdown resources and our generated orphans are managed.
    Unrelated local Claude skills/resources are retained. All source metadata
    and destination paths are validated before making any changes.
    """
    root = root.resolve()
    source_root = root / ".agents/skills"
    destination_root = root / ".claude/skills"
    if not source_root.is_dir():
        raise FileNotFoundError(f"canonical skills directory missing: {source_root}")
    expected: dict[Path, str] = {}
    for entry in sorted(source_root.glob("*/SKILL.md")):
        for source in sorted(entry.parent.rglob("*.md")):
            destination = destination_root / source.relative_to(source_root)
            expected[destination] = _wrapper(source, root)
    changes: dict[Path, str | None] = {
        path: text for path, text in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != text
    }
    for path in destination_root.rglob("*.md"):
        if path not in expected and GENERATED in path.read_text(encoding="utf-8"):
            changes[path] = None
    # A junction or symlink must never turn sync into a write outside this repo.
    for path in changes:
        if not path.resolve().is_relative_to(destination_root):
            raise ValueError(f"discovery path escapes the repository: {path}")
    if not check:
        for path, text in changes.items():
            if text is None:
                path.unlink()
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    return sorted(path.relative_to(root).as_posix() for path in changes)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args(argv)
    try:
        changed = sync(REPO_ROOT, check=args.check)
    except (OSError, ValueError) as error:
        parser.exit(2, f"agent setup: {error}\n")
    ok = not (args.check and changed)
    print(json.dumps({"ok": ok, "check": args.check, "changed": changed}))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
